language: ruby
bundler_args: --without development
rvm:
  - "1.9.3"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - mysql -e 'create database contribute_test;'
  - RAILS_ENV=test bundle exec rake sunspot:solr:start
  - RAILS_ENV=test bundle exec rake db:migrate
script:
  - bundle exec rake spec
