require 'spec_helper'
require 'integration_helper'

feature 'Projects', :focus do

  let(:projects) { 4.times.map { create :project, state: :active } }

  scenario 'index' do
    visit projects_path
    expect(page).to have_content projects.first.name
  end

  describe 'blocking process' do
    let(:admin) { create :user, admin: true }
    before { login_as admin }

    before do
      visit project_path(project)
      click_button 'Block Project'
      expect(page).to have_content 'Successfully blocked'
      expect(current_path).to eq project_path(project)
      click_button 'Unblock Project'
      expect(page).to have_content 'Successfully unblocked'
    end

    context 'starting with unconfirmed project' do
      let(:project) { create :project, payment_account_id: Project::UNDEFINED_PAYMENT_ACCOUNT_ID, state: :unconfirmed }

      scenario "should set the project state to 'unconfirmed'" do
        expect(project.reload.state).to eq :unconfirmed
      end
    end

    context 'starting with inactive project' do
      # NOTE
      # This payment account ID was generated by creating a new project, confirming it through amazon, and then looking at the generated value.
      # This will be different for each project in the real application
      # TODO Move this into a factory, perhaps with a helper method to generate a random string of the same format.
      let(:project) { create :project, payment_account_id: 'I4TRNV21A5A6BNEZGJI43QUP2X2CX3D7ID5RQMM8UK6DKJLZDSDXKDRE5BD3QXBL', state: :inactive }

      scenario "should set the project state to 'unconfirmed'" do
        expect(project.reload.state).to eq :inactive
      end
    end

    context 'starting with active project' do
      let(:project) { create :project, payment_account_id: 'I4TRNV21A5A6BNEZGJI43QUP2X2CX3D7ID5RQMM8UK6DKJLZDSDXKDRE5BD3QXBL', state: :active }

      scenario "should set the project state to 'unconfirmed'" do
        expect(project.reload.state).to eq :inactive
      end
    end
  end
end
